import { Cat } from '@/types';

export const mockCats: Cat[] = [
  {
    id: '1',
    name: 'Luna',
    age: '2 anos',
    breed: 'Siames',
    gender: 'female',
    description: 'Luna e uma gatinha docil e carinhosa que adora um colo. Ela foi resgatada da rua e agora busca um lar cheio de amor.',
    personality: ['Carinhosa', 'Calma', 'Brincalhona'],
    images: [
      'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800',
      'https://images.unsplash.com/photo-1513245543132-31f507417b26?w=800',
    ],
    location: {
      city: 'Sao Paulo',
      state: 'SP',
      neighborhood: 'Pinheiros',
    },
    owner: {
      name: 'Maria Silva',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
      whatsapp: '11999999999',
    },
    vaccinated: true,
    neutered: true,
    goodWith: { kids: true, dogs: false, cats: true },
    createdAt: '2024-01-15',
    featured: true,
  },
  {
    id: '2',
    name: 'Simba',
    age: '8 meses',
    breed: 'Laranjinha',
    gender: 'male',
    description: 'Simba e um filhote cheio de energia! Adora brincar e explorar cada cantinho da casa. Perfeito para familias ativas.',
    personality: ['Energetico', 'Curioso', 'Afetuoso'],
    images: [
      'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=800',
      'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=800',
    ],
    location: {
      city: 'Rio de Janeiro',
      state: 'RJ',
      neighborhood: 'Botafogo',
    },
    owner: {
      name: 'Carlos Santos',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
      whatsapp: '21988888888',
    },
    vaccinated: true,
    neutered: false,
    goodWith: { kids: true, dogs: true, cats: true },
    createdAt: '2024-01-20',
    featured: true,
  },
  {
    id: '3',
    name: 'Mia',
    age: '3 anos',
    breed: 'Persa',
    gender: 'female',
    description: 'Mia e uma princesa! Gosta de ambientes tranquilos e adora ser escovada. Ideal para apartamentos.',
    personality: ['Elegante', 'Independente', 'Tranquila'],
    images: [
      'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800',
      'https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?w=800',
    ],
    location: {
      city: 'Curitiba',
      state: 'PR',
      neighborhood: 'Batel',
    },
    owner: {
      name: 'Ana Costa',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
      whatsapp: '41977777777',
    },
    vaccinated: true,
    neutered: true,
    healthInfo: 'Precisa de racao especial para pelos longos',
    goodWith: { kids: false, dogs: false, cats: true },
    createdAt: '2024-01-18',
  },
  {
    id: '4',
    name: 'Thor',
    age: '1 ano',
    breed: 'Vira-lata',
    gender: 'male',
    description: 'Thor e um gato forte e protetor! Foi encontrado em uma obra e se tornou o mascote do lugar. Agora busca um lar definitivo.',
    personality: ['Corajoso', 'Leal', 'Brincalhao'],
    images: [
      'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=800',
      'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?w=800',
    ],
    location: {
      city: 'Belo Horizonte',
      state: 'MG',
      neighborhood: 'Savassi',
    },
    owner: {
      name: 'Pedro Oliveira',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
      whatsapp: '31966666666',
    },
    vaccinated: true,
    neutered: true,
    goodWith: { kids: true, dogs: true, cats: false },
    createdAt: '2024-01-22',
    featured: true,
  },
  {
    id: '5',
    name: 'Mel',
    age: '4 meses',
    breed: 'Frajola',
    gender: 'female',
    description: 'Mel e uma fofura de filhote! Com suas patinhas brancas e olhos verdes, conquista todos que a conhecem.',
    personality: ['Fofa', 'Dorminhoca', 'Carente'],
    images: [
      'https://images.unsplash.com/photo-1606214174585-fe31582dc6ee?w=800',
      'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=800',
    ],
    location: {
      city: 'Porto Alegre',
      state: 'RS',
      neighborhood: 'Moinhos de Vento',
    },
    owner: {
      name: 'Julia Lima',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
      whatsapp: '51955555555',
    },
    vaccinated: true,
    neutered: false,
    goodWith: { kids: true, dogs: true, cats: true },
    createdAt: '2024-01-25',
  },
  {
    id: '6',
    name: 'Bob',
    age: '5 anos',
    breed: 'Vira-lata',
    gender: 'male',
    description: 'Bob e um senhor gato muito sabio! Calmo e observador, ele gosta de ficar na janela vendo o movimento.',
    personality: ['Calmo', 'Observador', 'Companeiro'],
    images: [
      'https://images.unsplash.com/photo-1571566882372-1598d88abd90?w=800',
      'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=800',
    ],
    location: {
      city: 'Salvador',
      state: 'BA',
      neighborhood: 'Barra',
    },
    owner: {
      name: 'Roberto Souza',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      whatsapp: '71944444444',
    },
    vaccinated: true,
    neutered: true,
    goodWith: { kids: true, dogs: false, cats: true },
    createdAt: '2024-01-10',
  },
];

export const cities = [
  'Sao Paulo',
  'Rio de Janeiro',
  'Curitiba',
  'Belo Horizonte',
  'Porto Alegre',
  'Salvador',
];
